version: "3"

# go-task Taskfile
# https://taskfile.dev

dotenv: [".env"]
silent: true

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task --list

  lint:
    desc: "Run code linters"
    cmds:
      - golangci-lint run --config ./.golangci.yml
      - ifaceguard --config ifaceguard.cfg

  test:
    desc: "Run unit tests"
    cmds:
      - go test -race ./...

  fmt:
    desc: "Format the codebase"
    cmds:
      - go fmt ./...

  vet:
    desc: "Run go vet"
    cmds:
      - go vet ./...

  generate:
    desc: Generate code
    cmds:
      - go generate ./...

  build:
    desc: "Build the project"
    cmds:
      - go build -o bin/yandex-mcp ./cmd/yandex-mcp

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test ./... -coverprofile=coverage.out -v
      - go tool cover -html=coverage.out -o coverage.html
