version: "3"

# go-task Taskfile
# https://taskfile.dev

dotenv: [".env"]
silent: true

env:
  GOTOOLCHAIN:
    sh: awk '$1 == "go" { print "go" $2; exit }' go.mod

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task --list

  lint:
    desc: "Run code linters"
    cmds:
      - go tool golangci-lint run --config ./.golangci.yml
      - go tool ifaceguard --config ifaceguard.cfg
      - go tool govulncheck ./...

  test:
    desc: "Run unit tests"
    cmds:
      - go test -race ./...

  fmt:
    desc: "Format the codebase"
    cmds:
      - go fmt ./...
      - go tool golangci-lint fmt --config .golangci.yml ./...

  fix:
    desc: "Run go fix the codebase"
    cmds:
      - go fix ./...

  generate:
    desc: Generate code
    cmds:
      - go generate ./...

  build:
    desc: "Build the project"
    cmds:
      - go build -o bin/yandex-mcp ./cmd/yandex-mcp

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test ./... -coverprofile=coverage.out -v
      - go tool cover -html=coverage.out -o coverage.html

  vet:
    desc: "Run go vet"
    cmds:
      - go vet ./...
