// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	reflect "reflect"

	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
	gomock "go.uber.org/mock/gomock"
)

// MockIToolsRegistrator is a mock of IToolsRegistrator interface.
type MockIToolsRegistrator struct {
	ctrl     *gomock.Controller
	recorder *MockIToolsRegistratorMockRecorder
	isgomock struct{}
}

// MockIToolsRegistratorMockRecorder is the mock recorder for MockIToolsRegistrator.
type MockIToolsRegistratorMockRecorder struct {
	mock *MockIToolsRegistrator
}

// NewMockIToolsRegistrator creates a new mock instance.
func NewMockIToolsRegistrator(ctrl *gomock.Controller) *MockIToolsRegistrator {
	mock := &MockIToolsRegistrator{ctrl: ctrl}
	mock.recorder = &MockIToolsRegistratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToolsRegistrator) EXPECT() *MockIToolsRegistratorMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockIToolsRegistrator) Register(srv *mcp.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", srv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockIToolsRegistratorMockRecorder) Register(srv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIToolsRegistrator)(nil).Register), srv)
}
