// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=apihelpers
//

// Package apihelpers is a generated GoMock package.
package apihelpers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITokenProvider is a mock of ITokenProvider interface.
type MockITokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockITokenProviderMockRecorder
	isgomock struct{}
}

// MockITokenProviderMockRecorder is the mock recorder for MockITokenProvider.
type MockITokenProviderMockRecorder struct {
	mock *MockITokenProvider
}

// NewMockITokenProvider creates a new mock instance.
func NewMockITokenProvider(ctrl *gomock.Controller) *MockITokenProvider {
	mock := &MockITokenProvider{ctrl: ctrl}
	mock.recorder = &MockITokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenProvider) EXPECT() *MockITokenProviderMockRecorder {
	return m.recorder
}

// Token mocks base method.
func (m *MockITokenProvider) Token(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Token indicates an expected call of Token.
func (mr *MockITokenProviderMockRecorder) Token(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockITokenProvider)(nil).Token), ctx)
}
