// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=tracker
//

// Package tracker is a generated GoMock package.
package tracker

import (
	context "context"
	reflect "reflect"

	domain "github.com/n-r-w/yandex-mcp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockITrackerAdapter is a mock of ITrackerAdapter interface.
type MockITrackerAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockITrackerAdapterMockRecorder
	isgomock struct{}
}

// MockITrackerAdapterMockRecorder is the mock recorder for MockITrackerAdapter.
type MockITrackerAdapterMockRecorder struct {
	mock *MockITrackerAdapter
}

// NewMockITrackerAdapter creates a new mock instance.
func NewMockITrackerAdapter(ctrl *gomock.Controller) *MockITrackerAdapter {
	mock := &MockITrackerAdapter{ctrl: ctrl}
	mock.recorder = &MockITrackerAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITrackerAdapter) EXPECT() *MockITrackerAdapterMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockITrackerAdapter) AddComment(ctx context.Context, req *domain.TrackerCommentAddRequest) (*domain.TrackerCommentAddResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", ctx, req)
	ret0, _ := ret[0].(*domain.TrackerCommentAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockITrackerAdapterMockRecorder) AddComment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockITrackerAdapter)(nil).AddComment), ctx, req)
}

// CountIssues mocks base method.
func (m *MockITrackerAdapter) CountIssues(ctx context.Context, opts domain.TrackerCountIssuesOpts) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountIssues", ctx, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountIssues indicates an expected call of CountIssues.
func (mr *MockITrackerAdapterMockRecorder) CountIssues(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountIssues", reflect.TypeOf((*MockITrackerAdapter)(nil).CountIssues), ctx, opts)
}

// CreateIssue mocks base method.
func (m *MockITrackerAdapter) CreateIssue(ctx context.Context, req *domain.TrackerIssueCreateRequest) (*domain.TrackerIssueCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", ctx, req)
	ret0, _ := ret[0].(*domain.TrackerIssueCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIssue indicates an expected call of CreateIssue.
func (mr *MockITrackerAdapterMockRecorder) CreateIssue(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockITrackerAdapter)(nil).CreateIssue), ctx, req)
}

// ExecuteTransition mocks base method.
func (m *MockITrackerAdapter) ExecuteTransition(ctx context.Context, req *domain.TrackerTransitionExecuteRequest) (*domain.TrackerTransitionExecuteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTransition", ctx, req)
	ret0, _ := ret[0].(*domain.TrackerTransitionExecuteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTransition indicates an expected call of ExecuteTransition.
func (mr *MockITrackerAdapterMockRecorder) ExecuteTransition(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTransition", reflect.TypeOf((*MockITrackerAdapter)(nil).ExecuteTransition), ctx, req)
}

// GetIssue mocks base method.
func (m *MockITrackerAdapter) GetIssue(ctx context.Context, issueID string, opts domain.TrackerGetIssueOpts) (*domain.TrackerIssue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssue", ctx, issueID, opts)
	ret0, _ := ret[0].(*domain.TrackerIssue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssue indicates an expected call of GetIssue.
func (mr *MockITrackerAdapterMockRecorder) GetIssue(ctx, issueID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssue", reflect.TypeOf((*MockITrackerAdapter)(nil).GetIssue), ctx, issueID, opts)
}

// ListIssueComments mocks base method.
func (m *MockITrackerAdapter) ListIssueComments(ctx context.Context, issueID string, opts domain.TrackerListCommentsOpts) (*domain.TrackerCommentsPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssueComments", ctx, issueID, opts)
	ret0, _ := ret[0].(*domain.TrackerCommentsPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssueComments indicates an expected call of ListIssueComments.
func (mr *MockITrackerAdapterMockRecorder) ListIssueComments(ctx, issueID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssueComments", reflect.TypeOf((*MockITrackerAdapter)(nil).ListIssueComments), ctx, issueID, opts)
}

// ListIssueTransitions mocks base method.
func (m *MockITrackerAdapter) ListIssueTransitions(ctx context.Context, issueID string) ([]domain.TrackerTransition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssueTransitions", ctx, issueID)
	ret0, _ := ret[0].([]domain.TrackerTransition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssueTransitions indicates an expected call of ListIssueTransitions.
func (mr *MockITrackerAdapterMockRecorder) ListIssueTransitions(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssueTransitions", reflect.TypeOf((*MockITrackerAdapter)(nil).ListIssueTransitions), ctx, issueID)
}

// ListQueues mocks base method.
func (m *MockITrackerAdapter) ListQueues(ctx context.Context, opts domain.TrackerListQueuesOpts) (*domain.TrackerQueuesPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQueues", ctx, opts)
	ret0, _ := ret[0].(*domain.TrackerQueuesPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQueues indicates an expected call of ListQueues.
func (mr *MockITrackerAdapterMockRecorder) ListQueues(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQueues", reflect.TypeOf((*MockITrackerAdapter)(nil).ListQueues), ctx, opts)
}

// SearchIssues mocks base method.
func (m *MockITrackerAdapter) SearchIssues(ctx context.Context, opts domain.TrackerSearchIssuesOpts) (*domain.TrackerIssuesPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchIssues", ctx, opts)
	ret0, _ := ret[0].(*domain.TrackerIssuesPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIssues indicates an expected call of SearchIssues.
func (mr *MockITrackerAdapterMockRecorder) SearchIssues(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIssues", reflect.TypeOf((*MockITrackerAdapter)(nil).SearchIssues), ctx, opts)
}

// UpdateIssue mocks base method.
func (m *MockITrackerAdapter) UpdateIssue(ctx context.Context, req *domain.TrackerIssueUpdateRequest) (*domain.TrackerIssueUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIssue", ctx, req)
	ret0, _ := ret[0].(*domain.TrackerIssueUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIssue indicates an expected call of UpdateIssue.
func (mr *MockITrackerAdapterMockRecorder) UpdateIssue(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIssue", reflect.TypeOf((*MockITrackerAdapter)(nil).UpdateIssue), ctx, req)
}
