// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=authagent
//

// Package authagent is a generated GoMock package.
package authagent

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITokenSource is a mock of ITokenSource interface.
type MockITokenSource struct {
	ctrl     *gomock.Controller
	recorder *MockITokenSourceMockRecorder
	isgomock struct{}
}

// MockITokenSourceMockRecorder is the mock recorder for MockITokenSource.
type MockITokenSourceMockRecorder struct {
	mock *MockITokenSource
}

// NewMockITokenSource creates a new mock instance.
func NewMockITokenSource(ctrl *gomock.Controller) *MockITokenSource {
	mock := &MockITokenSource{ctrl: ctrl}
	mock.recorder = &MockITokenSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenSource) EXPECT() *MockITokenSourceMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockITokenSource) Acquire(ctx context.Context, profile string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, profile)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockITokenSourceMockRecorder) Acquire(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockITokenSource)(nil).Acquire), ctx, profile)
}
