// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=wiki
//

// Package wiki is a generated GoMock package.
package wiki

import (
	context "context"
	reflect "reflect"

	domain "github.com/n-r-w/yandex-mcp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIWikiAdapter is a mock of IWikiAdapter interface.
type MockIWikiAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockIWikiAdapterMockRecorder
	isgomock struct{}
}

// MockIWikiAdapterMockRecorder is the mock recorder for MockIWikiAdapter.
type MockIWikiAdapterMockRecorder struct {
	mock *MockIWikiAdapter
}

// NewMockIWikiAdapter creates a new mock instance.
func NewMockIWikiAdapter(ctrl *gomock.Controller) *MockIWikiAdapter {
	mock := &MockIWikiAdapter{ctrl: ctrl}
	mock.recorder = &MockIWikiAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWikiAdapter) EXPECT() *MockIWikiAdapterMockRecorder {
	return m.recorder
}

// AddGridColumns mocks base method.
func (m *MockIWikiAdapter) AddGridColumns(ctx context.Context, req domain.WikiGridColumnsAddRequest) (*domain.WikiRevisionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGridColumns", ctx, req)
	ret0, _ := ret[0].(*domain.WikiRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddGridColumns indicates an expected call of AddGridColumns.
func (mr *MockIWikiAdapterMockRecorder) AddGridColumns(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGridColumns", reflect.TypeOf((*MockIWikiAdapter)(nil).AddGridColumns), ctx, req)
}

// AddGridRows mocks base method.
func (m *MockIWikiAdapter) AddGridRows(ctx context.Context, req domain.WikiGridRowsAddRequest) (*domain.WikiGridRowsAddResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGridRows", ctx, req)
	ret0, _ := ret[0].(*domain.WikiGridRowsAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddGridRows indicates an expected call of AddGridRows.
func (mr *MockIWikiAdapterMockRecorder) AddGridRows(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGridRows", reflect.TypeOf((*MockIWikiAdapter)(nil).AddGridRows), ctx, req)
}

// AppendPage mocks base method.
func (m *MockIWikiAdapter) AppendPage(ctx context.Context, req *domain.WikiPageAppendRequest) (*domain.WikiPageAppendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendPage", ctx, req)
	ret0, _ := ret[0].(*domain.WikiPageAppendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendPage indicates an expected call of AppendPage.
func (mr *MockIWikiAdapterMockRecorder) AppendPage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendPage", reflect.TypeOf((*MockIWikiAdapter)(nil).AppendPage), ctx, req)
}

// CloneGrid mocks base method.
func (m *MockIWikiAdapter) CloneGrid(ctx context.Context, req domain.WikiGridCloneRequest) (*domain.WikiCloneOperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneGrid", ctx, req)
	ret0, _ := ret[0].(*domain.WikiCloneOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneGrid indicates an expected call of CloneGrid.
func (mr *MockIWikiAdapterMockRecorder) CloneGrid(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneGrid", reflect.TypeOf((*MockIWikiAdapter)(nil).CloneGrid), ctx, req)
}

// ClonePage mocks base method.
func (m *MockIWikiAdapter) ClonePage(ctx context.Context, req domain.WikiPageCloneRequest) (*domain.WikiCloneOperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClonePage", ctx, req)
	ret0, _ := ret[0].(*domain.WikiCloneOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClonePage indicates an expected call of ClonePage.
func (mr *MockIWikiAdapterMockRecorder) ClonePage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClonePage", reflect.TypeOf((*MockIWikiAdapter)(nil).ClonePage), ctx, req)
}

// CreateGrid mocks base method.
func (m *MockIWikiAdapter) CreateGrid(ctx context.Context, req *domain.WikiGridCreateRequest) (*domain.WikiGridCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGrid", ctx, req)
	ret0, _ := ret[0].(*domain.WikiGridCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGrid indicates an expected call of CreateGrid.
func (mr *MockIWikiAdapterMockRecorder) CreateGrid(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGrid", reflect.TypeOf((*MockIWikiAdapter)(nil).CreateGrid), ctx, req)
}

// CreatePage mocks base method.
func (m *MockIWikiAdapter) CreatePage(ctx context.Context, req *domain.WikiPageCreateRequest) (*domain.WikiPageCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePage", ctx, req)
	ret0, _ := ret[0].(*domain.WikiPageCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePage indicates an expected call of CreatePage.
func (mr *MockIWikiAdapterMockRecorder) CreatePage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePage", reflect.TypeOf((*MockIWikiAdapter)(nil).CreatePage), ctx, req)
}

// DeleteGrid mocks base method.
func (m *MockIWikiAdapter) DeleteGrid(ctx context.Context, gridID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGrid", ctx, gridID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGrid indicates an expected call of DeleteGrid.
func (mr *MockIWikiAdapterMockRecorder) DeleteGrid(ctx, gridID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGrid", reflect.TypeOf((*MockIWikiAdapter)(nil).DeleteGrid), ctx, gridID)
}

// DeleteGridColumns mocks base method.
func (m *MockIWikiAdapter) DeleteGridColumns(ctx context.Context, req domain.WikiGridColumnsDeleteRequest) (*domain.WikiRevisionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGridColumns", ctx, req)
	ret0, _ := ret[0].(*domain.WikiRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGridColumns indicates an expected call of DeleteGridColumns.
func (mr *MockIWikiAdapterMockRecorder) DeleteGridColumns(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGridColumns", reflect.TypeOf((*MockIWikiAdapter)(nil).DeleteGridColumns), ctx, req)
}

// DeleteGridRows mocks base method.
func (m *MockIWikiAdapter) DeleteGridRows(ctx context.Context, req domain.WikiGridRowsDeleteRequest) (*domain.WikiRevisionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGridRows", ctx, req)
	ret0, _ := ret[0].(*domain.WikiRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGridRows indicates an expected call of DeleteGridRows.
func (mr *MockIWikiAdapterMockRecorder) DeleteGridRows(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGridRows", reflect.TypeOf((*MockIWikiAdapter)(nil).DeleteGridRows), ctx, req)
}

// DeletePage mocks base method.
func (m *MockIWikiAdapter) DeletePage(ctx context.Context, pageID string) (*domain.WikiPageDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePage", ctx, pageID)
	ret0, _ := ret[0].(*domain.WikiPageDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePage indicates an expected call of DeletePage.
func (mr *MockIWikiAdapterMockRecorder) DeletePage(ctx, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePage", reflect.TypeOf((*MockIWikiAdapter)(nil).DeletePage), ctx, pageID)
}

// GetGridByID mocks base method.
func (m *MockIWikiAdapter) GetGridByID(ctx context.Context, gridID string, opts domain.WikiGetGridOpts) (*domain.WikiGrid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGridByID", ctx, gridID, opts)
	ret0, _ := ret[0].(*domain.WikiGrid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGridByID indicates an expected call of GetGridByID.
func (mr *MockIWikiAdapterMockRecorder) GetGridByID(ctx, gridID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGridByID", reflect.TypeOf((*MockIWikiAdapter)(nil).GetGridByID), ctx, gridID, opts)
}

// GetPageByID mocks base method.
func (m *MockIWikiAdapter) GetPageByID(ctx context.Context, id string, opts domain.WikiGetPageOpts) (*domain.WikiPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageByID", ctx, id, opts)
	ret0, _ := ret[0].(*domain.WikiPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageByID indicates an expected call of GetPageByID.
func (mr *MockIWikiAdapterMockRecorder) GetPageByID(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageByID", reflect.TypeOf((*MockIWikiAdapter)(nil).GetPageByID), ctx, id, opts)
}

// GetPageBySlug mocks base method.
func (m *MockIWikiAdapter) GetPageBySlug(ctx context.Context, slug string, opts domain.WikiGetPageOpts) (*domain.WikiPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageBySlug", ctx, slug, opts)
	ret0, _ := ret[0].(*domain.WikiPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageBySlug indicates an expected call of GetPageBySlug.
func (mr *MockIWikiAdapterMockRecorder) GetPageBySlug(ctx, slug, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageBySlug", reflect.TypeOf((*MockIWikiAdapter)(nil).GetPageBySlug), ctx, slug, opts)
}

// ListPageGrids mocks base method.
func (m *MockIWikiAdapter) ListPageGrids(ctx context.Context, pageID string, opts domain.WikiListGridsOpts) (*domain.WikiGridsPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPageGrids", ctx, pageID, opts)
	ret0, _ := ret[0].(*domain.WikiGridsPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPageGrids indicates an expected call of ListPageGrids.
func (mr *MockIWikiAdapterMockRecorder) ListPageGrids(ctx, pageID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPageGrids", reflect.TypeOf((*MockIWikiAdapter)(nil).ListPageGrids), ctx, pageID, opts)
}

// ListPageResources mocks base method.
func (m *MockIWikiAdapter) ListPageResources(ctx context.Context, pageID string, opts domain.WikiListResourcesOpts) (*domain.WikiResourcesPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPageResources", ctx, pageID, opts)
	ret0, _ := ret[0].(*domain.WikiResourcesPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPageResources indicates an expected call of ListPageResources.
func (mr *MockIWikiAdapterMockRecorder) ListPageResources(ctx, pageID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPageResources", reflect.TypeOf((*MockIWikiAdapter)(nil).ListPageResources), ctx, pageID, opts)
}

// MoveGridColumns mocks base method.
func (m *MockIWikiAdapter) MoveGridColumns(ctx context.Context, req domain.WikiGridColumnsMoveRequest) (*domain.WikiRevisionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveGridColumns", ctx, req)
	ret0, _ := ret[0].(*domain.WikiRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveGridColumns indicates an expected call of MoveGridColumns.
func (mr *MockIWikiAdapterMockRecorder) MoveGridColumns(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveGridColumns", reflect.TypeOf((*MockIWikiAdapter)(nil).MoveGridColumns), ctx, req)
}

// MoveGridRows mocks base method.
func (m *MockIWikiAdapter) MoveGridRows(ctx context.Context, req domain.WikiGridRowsMoveRequest) (*domain.WikiRevisionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveGridRows", ctx, req)
	ret0, _ := ret[0].(*domain.WikiRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveGridRows indicates an expected call of MoveGridRows.
func (mr *MockIWikiAdapterMockRecorder) MoveGridRows(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveGridRows", reflect.TypeOf((*MockIWikiAdapter)(nil).MoveGridRows), ctx, req)
}

// UpdateGridCells mocks base method.
func (m *MockIWikiAdapter) UpdateGridCells(ctx context.Context, req *domain.WikiGridCellsUpdateRequest) (*domain.WikiGridCellsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGridCells", ctx, req)
	ret0, _ := ret[0].(*domain.WikiGridCellsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGridCells indicates an expected call of UpdateGridCells.
func (mr *MockIWikiAdapterMockRecorder) UpdateGridCells(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGridCells", reflect.TypeOf((*MockIWikiAdapter)(nil).UpdateGridCells), ctx, req)
}

// UpdatePage mocks base method.
func (m *MockIWikiAdapter) UpdatePage(ctx context.Context, req *domain.WikiPageUpdateRequest) (*domain.WikiPageUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePage", ctx, req)
	ret0, _ := ret[0].(*domain.WikiPageUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePage indicates an expected call of UpdatePage.
func (mr *MockIWikiAdapterMockRecorder) UpdatePage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePage", reflect.TypeOf((*MockIWikiAdapter)(nil).UpdatePage), ctx, req)
}
