// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=wiki
//

// Package wiki is a generated GoMock package.
package wiki

import (
	context "context"
	reflect "reflect"

	domain "github.com/n-r-w/yandex-mcp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIWikiAdapter is a mock of IWikiAdapter interface.
type MockIWikiAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockIWikiAdapterMockRecorder
	isgomock struct{}
}

// MockIWikiAdapterMockRecorder is the mock recorder for MockIWikiAdapter.
type MockIWikiAdapterMockRecorder struct {
	mock *MockIWikiAdapter
}

// NewMockIWikiAdapter creates a new mock instance.
func NewMockIWikiAdapter(ctrl *gomock.Controller) *MockIWikiAdapter {
	mock := &MockIWikiAdapter{ctrl: ctrl}
	mock.recorder = &MockIWikiAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWikiAdapter) EXPECT() *MockIWikiAdapterMockRecorder {
	return m.recorder
}

// AppendPage mocks base method.
func (m *MockIWikiAdapter) AppendPage(ctx context.Context, req *domain.WikiPageAppendRequest) (*domain.WikiPageAppendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendPage", ctx, req)
	ret0, _ := ret[0].(*domain.WikiPageAppendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendPage indicates an expected call of AppendPage.
func (mr *MockIWikiAdapterMockRecorder) AppendPage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendPage", reflect.TypeOf((*MockIWikiAdapter)(nil).AppendPage), ctx, req)
}

// CreateGrid mocks base method.
func (m *MockIWikiAdapter) CreateGrid(ctx context.Context, req *domain.WikiGridCreateRequest) (*domain.WikiGridCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGrid", ctx, req)
	ret0, _ := ret[0].(*domain.WikiGridCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGrid indicates an expected call of CreateGrid.
func (mr *MockIWikiAdapterMockRecorder) CreateGrid(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGrid", reflect.TypeOf((*MockIWikiAdapter)(nil).CreateGrid), ctx, req)
}

// CreatePage mocks base method.
func (m *MockIWikiAdapter) CreatePage(ctx context.Context, req *domain.WikiPageCreateRequest) (*domain.WikiPageCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePage", ctx, req)
	ret0, _ := ret[0].(*domain.WikiPageCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePage indicates an expected call of CreatePage.
func (mr *MockIWikiAdapterMockRecorder) CreatePage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePage", reflect.TypeOf((*MockIWikiAdapter)(nil).CreatePage), ctx, req)
}

// GetGridByID mocks base method.
func (m *MockIWikiAdapter) GetGridByID(ctx context.Context, gridID string, opts domain.WikiGetGridOpts) (*domain.WikiGrid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGridByID", ctx, gridID, opts)
	ret0, _ := ret[0].(*domain.WikiGrid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGridByID indicates an expected call of GetGridByID.
func (mr *MockIWikiAdapterMockRecorder) GetGridByID(ctx, gridID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGridByID", reflect.TypeOf((*MockIWikiAdapter)(nil).GetGridByID), ctx, gridID, opts)
}

// GetPageByID mocks base method.
func (m *MockIWikiAdapter) GetPageByID(ctx context.Context, id int64, opts domain.WikiGetPageOpts) (*domain.WikiPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageByID", ctx, id, opts)
	ret0, _ := ret[0].(*domain.WikiPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageByID indicates an expected call of GetPageByID.
func (mr *MockIWikiAdapterMockRecorder) GetPageByID(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageByID", reflect.TypeOf((*MockIWikiAdapter)(nil).GetPageByID), ctx, id, opts)
}

// GetPageBySlug mocks base method.
func (m *MockIWikiAdapter) GetPageBySlug(ctx context.Context, slug string, opts domain.WikiGetPageOpts) (*domain.WikiPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageBySlug", ctx, slug, opts)
	ret0, _ := ret[0].(*domain.WikiPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageBySlug indicates an expected call of GetPageBySlug.
func (mr *MockIWikiAdapterMockRecorder) GetPageBySlug(ctx, slug, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageBySlug", reflect.TypeOf((*MockIWikiAdapter)(nil).GetPageBySlug), ctx, slug, opts)
}

// ListPageGrids mocks base method.
func (m *MockIWikiAdapter) ListPageGrids(ctx context.Context, pageID int64, opts domain.WikiListGridsOpts) (*domain.WikiGridsPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPageGrids", ctx, pageID, opts)
	ret0, _ := ret[0].(*domain.WikiGridsPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPageGrids indicates an expected call of ListPageGrids.
func (mr *MockIWikiAdapterMockRecorder) ListPageGrids(ctx, pageID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPageGrids", reflect.TypeOf((*MockIWikiAdapter)(nil).ListPageGrids), ctx, pageID, opts)
}

// ListPageResources mocks base method.
func (m *MockIWikiAdapter) ListPageResources(ctx context.Context, pageID int64, opts domain.WikiListResourcesOpts) (*domain.WikiResourcesPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPageResources", ctx, pageID, opts)
	ret0, _ := ret[0].(*domain.WikiResourcesPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPageResources indicates an expected call of ListPageResources.
func (mr *MockIWikiAdapterMockRecorder) ListPageResources(ctx, pageID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPageResources", reflect.TypeOf((*MockIWikiAdapter)(nil).ListPageResources), ctx, pageID, opts)
}

// UpdateGridCells mocks base method.
func (m *MockIWikiAdapter) UpdateGridCells(ctx context.Context, req *domain.WikiGridCellsUpdateRequest) (*domain.WikiGridCellsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGridCells", ctx, req)
	ret0, _ := ret[0].(*domain.WikiGridCellsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGridCells indicates an expected call of UpdateGridCells.
func (mr *MockIWikiAdapterMockRecorder) UpdateGridCells(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGridCells", reflect.TypeOf((*MockIWikiAdapter)(nil).UpdateGridCells), ctx, req)
}

// UpdatePage mocks base method.
func (m *MockIWikiAdapter) UpdatePage(ctx context.Context, req *domain.WikiPageUpdateRequest) (*domain.WikiPageUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePage", ctx, req)
	ret0, _ := ret[0].(*domain.WikiPageUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePage indicates an expected call of UpdatePage.
func (mr *MockIWikiAdapterMockRecorder) UpdatePage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePage", reflect.TypeOf((*MockIWikiAdapter)(nil).UpdatePage), ctx, req)
}
