// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=token
//

// Package token is a generated GoMock package.
package ytoken

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICommandExecutor is a mock of ICommandExecutor interface.
type MockICommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockICommandExecutorMockRecorder
	isgomock struct{}
}

// MockICommandExecutorMockRecorder is the mock recorder for MockICommandExecutor.
type MockICommandExecutorMockRecorder struct {
	mock *MockICommandExecutor
}

// NewMockICommandExecutor creates a new mock instance.
func NewMockICommandExecutor(ctrl *gomock.Controller) *MockICommandExecutor {
	mock := &MockICommandExecutor{ctrl: ctrl}
	mock.recorder = &MockICommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICommandExecutor) EXPECT() *MockICommandExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockICommandExecutor) Execute(ctx context.Context, name string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Execute", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockICommandExecutorMockRecorder) Execute(ctx, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockICommandExecutor)(nil).Execute), varargs...)
}
